use rand::seq::IndexedRandom;
use skia_safe::{Color, FontStyle};

use meme_generator_core::error::Error;
use meme_generator_utils::{
    builder::InputImage,
    canvas::CanvasExt,
    encoder::encode_png,
    image::{Fit, ImageExt},
    text_params,
    tools::{color_from_hex_code, load_image, local_date, new_paint, new_surface},
};

use crate::{options::NoOptions, register_meme};

fn name_generator(images: Vec<InputImage>, _: Vec<String>, _: NoOptions) -> Result<Vec<u8>, Error> {
    let colors = ["#0000ff", "#ff00f7", "#00cc66"];
    let el1 = [
        "废墟",
        "深海",
        "反应堆",
        "学园",
        "腐烂",
        "东京",
        "三维",
        "四次元",
        "少管所",
        "流星",
        "闪光",
        "南极",
        "消极",
        "幽浮",
        "网路",
        "暗狱",
        "离子态",
        "液态",
        "黑色",
        "抱抱",
        "暴力",
        "垃圾",
        "社会",
        "残暴",
        "残酷",
        "工口",
        "戮尸",
        "原味",
        "毛茸茸",
        "香香",
        "霹雳",
        "午夜",
        "美工刀",
        "爆浆",
        "机关枪",
        "无响应",
        "手术台",
        "麻风病",
        "虚拟",
        "速冻",
        "智能",
        "2000",
        "甜味",
        "华丽",
        "反社会",
        "玛利亚",
        "无",
        "梦之",
        "蔷薇",
        "无政府",
        "酷酷",
        "西伯利亚",
        "人造",
        "法外",
        "追杀",
        "通缉",
        "女子",
        "微型",
        "男子",
        "超",
        "毁灭",
        "大型",
        "绝望",
        "阴间",
        "死亡",
        "坟场",
        "高科技",
        "奇妙",
        "魔法",
        "极限",
        "社会主义",
        "无聊",
    ];
    let el2 = [
        "小丑",
        "仿生",
        "纳米",
        "原子",
        "丧",
        "电子",
        "十字架",
        "咩咩",
        "赛博",
        "野猪",
        "外星",
        "窒息",
        "变态",
        "触手",
        "小众",
        "悲情",
        "飞行",
        "绿色",
        "电动",
        "铁锈",
        "碎尸",
        "电音",
        "蠕动",
        "酸甜",
        "虚构",
        "乱码",
        "碳水",
        "内脏",
        "脑浆",
        "血管",
        "全裸",
        "绷带",
        "不合格",
        "光滑",
        "标本",
        "酸性",
        "碱性",
        "404",
        "变身",
        "反常",
        "樱桃",
        "碳基",
        "矫情",
        "病娇",
        "进化",
        "潮湿",
        "砂糖",
        "高潮",
        "变异",
        "复合盐",
        "伏特加",
        "抑郁",
        "暴躁",
        "不爱说话",
        "废物",
        "失败",
        "幻想型",
        "社恐",
        "苦涩",
        "粘液",
        "浓厚",
        "快乐",
        "强制",
        "中二病",
        "恶魔",
        "emo",
        "激光",
        "发射",
        "限量版",
        "迷因",
        "堕落",
        "放射性",
    ];
    let el3 = [
        "天使",
        "精灵",
        "女孩",
        "男孩",
        "宝贝",
        "小妈咪",
        "虫",
        "菇",
        "公主",
        "少女",
        "少年",
        "1号机",
        "子",
        "恐龙",
        "蜈蚣",
        "蟑螂",
        "食人鱼",
        "小飞船",
        "舞女",
        "桃子",
        "团子",
        "精",
        "酱",
        "废料",
        "生物",
        "物质",
        "奶茶",
        "搅拌机",
        "液",
        "火锅",
        "祭司",
        "体",
        "实验品",
        "试验体",
        "小猫咪",
        "样本",
        "颗粒",
        "血块",
        "汽水",
        "蛙",
        "软体",
        "机器人",
        "人质",
        "小熊",
        "圣母",
        "胶囊",
        "乙女",
        "主义者",
        "屑",
        "垢",
        "污渍",
        "废人",
        "毛血旺",
        "怪人",
        "肉",
        "河豚",
        "豚",
        "藻类",
        "唾沫",
        "咒语",
        "建筑",
        "球",
        "小狗",
        "碳",
        "元素",
        "少先队员",
        "博士",
        "糖",
    ];

    let mut rng = rand::rng();
    let color = colors.choose(&mut rng).unwrap();
    let name = format!(
        "{}{}{}",
        el1.choose(&mut rng).unwrap(),
        el2.choose(&mut rng).unwrap(),
        el3.choose(&mut rng).unwrap()
    );

    let mut surface = new_surface((900, 900));
    let canvas = surface.canvas();
    canvas.clear(Color::from_rgb(225, 225, 225));
    let title = load_image("name_generator/0.png")?.resize_exact((700, 200));
    canvas.draw_image(&title, (100, 0), None);
    canvas.draw_text(
        (20, 450),
        "您的亚名是",
        40.0,
        text_params!(
            paint = new_paint(Color::from_rgb(105, 105, 105)),
            font_style = FontStyle::bold()
        ),
    );

    let img = images[0].image.resize_fit((490, 490), Fit::Cover);
    canvas.draw_image(&img, (310, 235), None);
    canvas.draw_text(
        (20, 620),
        &name,
        60.0,
        text_params!(
            paint = new_paint(color_from_hex_code(color)),
            font_style = FontStyle::bold()
        ),
    );
    encode_png(surface.image_snapshot())
}

register_meme!(
    "name_generator",
    name_generator,
    min_images = 1,
    max_images = 1,
    keywords = &["亚文化取名机", "亚名"],
    date_created = local_date(2023, 2, 4),
    date_modified = local_date(2023, 2, 14),
);
