name: Build

on:
  push:
    branches:
      - main
    paths:
      - "Cargo.toml"
      - "meme_generator/**"
      - "meme_generator_cli/**"
      - "meme_generator_core/**"
      - "meme_generator_memes/**"
      - "meme_generator_py/**"
      - "meme_generator_server/**"
      - "meme_generator_utils/**"
      - "meme_options_derive/**"
    tags:
      - "v*"
  pull_request_target:
    paths:
      - "Cargo.toml"
      - "meme_generator/**"
      - "meme_generator_cli/**"
      - "meme_generator_core/**"
      - "meme_generator_memes/**"
      - "meme_generator_py/**"
      - "meme_generator_server/**"
      - "meme_generator_utils/**"
      - "meme_options_derive/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64
          - runner: macos-latest
            target: x86_64-apple-darwin
            label: macos-x86_64
          - runner: macos-latest
            target: aarch64-apple-darwin
            label: macos-aarch64

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.83.0

      - uses: swatinem/rust-cache@v2

      - name: Rustup add target
        run: rustup target add ${{ matrix.platform.target }}

      - name: Build target
        run: cargo build --release --target ${{ matrix.platform.target }} --bin meme --features server

      - uses: actions/upload-artifact@v4
        with:
          name: "meme-generator-cli-${{ matrix.platform.label }}"
          path: |
            target/${{ matrix.platform.target }}/release/meme*
            !target/${{ matrix.platform.target }}/release/meme.d
            !target/${{ matrix.platform.target }}/release/meme.pdb

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          working-directory: meme_generator_py
          args: --release --out dist

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: meme-generator-wheels-${{ matrix.platform.label }}
          path: meme_generator_py/dist

  build_linux:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            container: ghcr.io/memecrafters/meme-generator-build-container:latest
            target: x86_64-unknown-linux-gnu
            label: linux-x86_64
          - runner: ubuntu-24.04-arm
            container: ghcr.io/memecrafters/meme-generator-build-container:arm64
            target: aarch64-unknown-linux-gnu
            label: linux-aarch64

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.83.0
      - uses: swatinem/rust-cache@v2

      - name: Rustup add target
        run: rustup target add ${{ matrix.platform.target }}

      - name: Build target
        run: cargo build --release --target ${{ matrix.platform.target }} --bin meme --features server,vendored,embed-freetype

      - uses: actions/upload-artifact@v4
        with:
          name: "meme-generator-cli-${{ matrix.platform.label }}"
          path: |
            target/${{ matrix.platform.target }}/release/meme*
            !target/${{ matrix.platform.target }}/release/meme.d

      - name: Build wheels
        run: |
          pip3 install pipx
          export PATH=$PATH:/github/home/.local/bin
          pipx install maturin
          pipx install patchelf
          maturin build --release --out dist --target ${{ matrix.platform.target }} --features vendored,embed-freetype
        working-directory: meme_generator_py

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: meme-generator-wheels-${{ matrix.platform.label }}
          path: meme_generator_py/dist

  build_android:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            container: ghcr.io/memecrafters/meme-generator-build-container:android
            target: aarch64-linux-android
            label: android-aarch64

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.83.0
      - uses: swatinem/rust-cache@v2

      - name: Rustup add target
        run: rustup target add ${{ matrix.platform.target }}

      - name: Build target
        run: cargo build --release --target ${{ matrix.platform.target }} --bin meme --features server,vendored

      - uses: actions/upload-artifact@v4
        with:
          name: "meme-generator-cli-${{ matrix.platform.label }}"
          path: |
            target/${{ matrix.platform.target }}/release/meme*
            !target/${{ matrix.platform.target }}/release/meme.d

  crates_io_publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build, build_linux, build_android]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.83.0
      - uses: swatinem/rust-cache@v2

      - name: Cargo login
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: Cargo Publish
        run: |
          cargo publish --package meme_generator_memes
          cargo publish --package meme_generator

  pypi_publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build, build_linux, build_android]
    steps:
      - uses: actions/download-artifact@v4

      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --non-interactive --skip-existing meme-generator-wheels-*/*

  release_draft:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build, build_linux, build_android]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dawidd6/action-download-artifact@v7
        with:
          skip_unpack: true
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref }}
          draft: true
          files: |
            meme-generator-cli-*
