name: Rebuild container
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: container
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/memecrafters/meme-generator-container:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
